### ISSUE TITLE
limit container Resources

### ISSUE THREAD

**Issue by fhauptmann** [hzi-braunschweig/SORMAS-Docker#9]
Ressoiurcenbeschränkungen für Container einrichten
Java VM: UseCGroups einschalten

maxramfraction entsprechend einstellen.

**Comment by TomHutter** [comment]
```
  healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M    
```
